plugins {
    id 'fabric-loom' version '1.14.10'
    id 'maven-publish'
}
apply plugin: 'fabric-loom'
apply plugin: 'maven-publish'

version = project.mod_version
group = project.maven_group

base {
    archivesName = project.archives_base_name
}

repositories {
    def localMaven = file("${project.rootDir}/.gradle/maven-repo")
    if (localMaven.exists()) {
        maven { url = localMaven.toURI(); metadataSources { artifact() } }
    }
    maven { url = "http://maven.fabricmc.net/"; allowInsecureProtocol = true }
    mavenCentral()
}

dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    mappings "net.fabricmc:yarn:${project.yarn_mappings}:v2"
    modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"
    // modImplementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}"

    compileOnly "org.lwjgl:lwjgl-vulkan:3.3.3"
    runtimeOnly "org.lwjgl:lwjgl-vulkan:3.3.3"
}

tasks.withType(JavaCompile).configureEach {
    it.options.encoding = "UTF-8"
    it.options.release.set(21)
}

java {
    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
    withSourcesJar()
}

jar {
    from("LICENSE") {
        rename { "${it}_${project.archivesBaseName}" }
    }
}

task printCompileClasspath {
    doLast {
        println sourceSets.main.compileClasspath.files.collect { it.absolutePath }
    }
}

task printSources {
    doLast {
        println sourceSets.main.java.srcDirs
    }
}

task printCompileJavaDetails {
    doLast {
        println "Source dirs: ${sourceSets.main.java.srcDirs}"
        println "Classpath:"
        sourceSets.main.compileClasspath.files.each { println "  ${it}" }
    }
}
