# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx2G -Djavax.net.ssl.trustStore=${project.rootDir}/.gradle/custom-cacerts -Djavax.net.ssl.trustStorePassword=changeit
org.gradle.parallel=true

# Fabric Properties
minecraft_version=1.21.11
yarn_mappings=1.21.11+build.1
loader_version=0.18.1

# Mod Properties
mod_version=1.0.0
maven_group=net.vulkanmod
archives_base_name=vulkanmod

# Dependencies
fabric_version=0.141.1+1.21.11
