allprojects {
    buildscript {
        repositories {
            maven {
                url "http://maven.fabricmc.net/"
                allowInsecureProtocol true
            }
            mavenCentral()
            gradlePluginPortal()
        }
    }
    repositories {
        maven {
            url "http://maven.fabricmc.net/"
            allowInsecureProtocol true
        }
        mavenCentral()
        gradlePluginPortal()
    }
}
