name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 21
          cache: gradle
      - uses: gradle/actions/setup-gradle@v4
      - run: java -version
      - run: gradle --version
      - run: gradle clean build --stacktrace --info 2>&1 | tee build.log
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: vulkanmod-build
          path: build/libs/*.jar
      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: build-log
          path: build.log
